sudo: required
services:
  - docker

before_install:
  - docker build -t nkavuri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nkavuri/react-test npm test -- --coverage

after_success:
  - docker build -t nkavuri/multi-client ./client
  - docker build -t nkavuri/multi-nginx ./nginx
  - docker build -t nkavuri/multi-server ./server
  - docker build -t nkavuri/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push nkavuri/multi-client
  - docker push nkavuri/multi-nginx
  - docker push nkavuri/multi-server
  - docker push nkavuri/multi-worker

  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker2"
  env: "Multidocker2-env"
  bucket_name: "elasticbeanstalk-us-east-2-235502769638"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
